#!/bin/sh
#
# init.d script for SimpleIRC Daemon
#
# chkconfig: 345 80 20
# description: SimpleIRC Daemon

### BEGIN INIT INFO
# Provides:          simpleircd
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop simpleirc server
### END INIT INFO

/opt/simpleirc/bin/simpleircctl.sh $1
